[package]
authors = ["prfss <gprfss4815@gmail.com>"]
edition = "2018"
name = "dft"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
